# Generated by Django 4.1.7 on 2023-02-17 19:51

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('type', models.CharField(choices=[('whatsapp_business_account_id', 'WhatsApp Business Account ID')], max_length=38, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('visible', models.BooleanField(default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
