# Generated by Django 3.1 on 2020-08-13 09:26

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import model_utils.fields
import simple_history.models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный')),
                ('type', utils.models.DynamicChoiceField(choices=[('accounts_password_change', 'Пользователь сменил пароль'), ('accounts_password_reset', 'Восстановление пароля'), ('accounts_password_set', 'Создание нового пароля'), ('accounts_email_confirm', 'Подтверждение адреса эл. почты')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('from_addr', models.CharField(blank=True, default='webmaster@localhost', max_length=255)),
                ('send_after_hours', models.FloatField(default=0, help_text='Delay before sending mail')),
                ('extra_recipients', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None)),
                ('cc_emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmailTemplate',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный')),
                ('type', utils.models.DynamicChoiceField(choices=[('accounts_password_change', 'Пользователь сменил пароль'), ('accounts_password_reset', 'Восстановление пароля'), ('accounts_password_set', 'Создание нового пароля'), ('accounts_email_confirm', 'Подтверждение адреса эл. почты')], db_index=True, max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('from_addr', models.CharField(blank=True, default='webmaster@localhost', max_length=255)),
                ('send_after_hours', models.FloatField(default=0, help_text='Delay before sending mail')),
                ('extra_recipients', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None)),
                ('cc_emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Шаблон письма',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
