version: '3.6'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - ./docker/volumes:/var/lib/postgresql/data

  web:
    environment:
      PYTHONDONTWRITEBYTECODE: 1

    build: .
    command: ['sh', 'service.web.sh']

    volumes:
      - ./project/:/code/
      - ./docker/service.web.sh:/code/service.web.sh

    links:
      - db

    ports:
      - "8000:8000"
