# Generated by Django 4.1.7 on 2023-02-18 17:44

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('source', models.CharField(choices=[('google_forms', 'Google Forms'), ('paybox', 'PayBox'), ('telegram', 'Telegram'), ('sendgrid', 'Sendgrid'), ('slack', 'Slack'), ('stripe', 'Stripe'), ('apple', 'Apple'), ('facebook_whatsapp', 'Facebook WhatsApp')], max_length=250)),
                ('remote_ip', models.GenericIPAddressField(default='127.0.0.1')),
                ('content', models.JSONField()),
                ('is_processed', models.BooleanField(default=False)),
                ('content_search', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name': 'Данные вебхука',
                'verbose_name_plural': 'Данные вебхуков',
            },
        ),
        migrations.AddIndex(
            model_name='webhookdata',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content_search'], name='webhooks_we_content_493db3_gin'),
        ),
    ]
