# Generated by Django 4.1.7 on 2023-02-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='whatsapp_enabled',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_enabled',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
    ]
