#!/bin/bash

export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8

FILES=$(git diff --cached --name-only --diff-filter=ACM)
PY_FILES=$(echo "$FILES" | grep ".*\.py$")
if [[ "$PY_FILES" != "" ]]; then
    echo "*** Running Python linter for the changed files list (flake8) ***"
    echo
    echo "Changed Python files list: "
    echo "$PY_FILES" | xargs -I {} echo " -  {}"
    echo

    pipenv run flake8 --config flake8.ini ${PY_FILES}
fi
