# Generated by Django 4.1.7 on 2023-03-02 14:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('business_account_id', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=255)),
                ('type', utils.fields.ChoiceField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('template', 'Template')], default='text', max_length=8)),
                ('date', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='whatsapp_messages')),
                ('raw_data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='whatsappphonenumber',
            name='type',
            field=utils.fields.ChoiceField(choices=[('contact', 'Contact'), ('system', 'System')], default='contact', max_length=7),
        ),
        migrations.AlterField(
            model_name='whatsappphonenumber',
            name='display',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('type', utils.fields.ChoiceField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], max_length=9)),
                ('date', models.DateTimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='whatsapp.whatsappmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='from_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_messages', to='whatsapp.whatsappphonenumber'),
        ),
        migrations.AddField(
            model_name='whatsappmessage',
            name='to_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_messages', to='whatsapp.whatsappphonenumber'),
        ),
    ]
