# Generated by Django 4.1.7 on 2023-02-17 19:51

import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KlaviyoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
