# Generated by Django 4.1.7 on 2023-02-17 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import simple_history.models
import utils.fields
import utils.json


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('klaviyo', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('vendor', utils.fields.ChoiceField(choices=[('klaviyo', 'Klaviyo'), ('whatsapp', 'Whatsapp')], max_length=8)),
                ('type', models.CharField(choices=[('accounts_login', 'Пользователь авторизовался'), ('accounts_signup', 'Пользователь зарегистрировался'), ('accounts_password_changed', 'Пользователь сменил пароль'), ('accounts_password_reset', 'Восстановление пароля'), ('accounts_password_reset_otp', 'Восстановление пароля одноразовым кодом'), ('accounts_password_set', 'Создание нового пароля'), ('accounts_email_confirm', 'Подтверждение адреса эл. почты')], max_length=50)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('klaviyo_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='klaviyo.klaviyoevent')),
                ('whatsapp_template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='whatsapp.whatsapptemplate')),
            ],
            options={
                'verbose_name': 'historical Шаблон письма',
                'verbose_name_plural': 'historical Шаблоны писем',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hash', models.SlugField()),
                ('direction', models.CharField(choices=[('incoming', 'Входящая'), ('outgoing', 'Исходящая')], default='outgoing', max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('manual', 'Ручная'), ('automatic', 'Автоматическая'), ('user', 'Пользователь')], default='automatic', max_length=20)),
                ('template_type', models.CharField(choices=[('accounts_login', 'Пользователь авторизовался'), ('accounts_signup', 'Пользователь зарегистрировался'), ('accounts_password_changed', 'Пользователь сменил пароль'), ('accounts_password_reset', 'Восстановление пароля'), ('accounts_password_reset_otp', 'Восстановление пароля одноразовым кодом'), ('accounts_password_set', 'Создание нового пароля'), ('accounts_email_confirm', 'Подтверждение адреса эл. почты')], db_index=True, max_length=50)),
                ('template_vendor', utils.fields.ChoiceField(blank=True, choices=[('klaviyo', 'Klaviyo'), ('whatsapp', 'Whatsapp')], max_length=8, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, encoder=utils.json.JSONEncoder, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_communications', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коммуникация',
                'verbose_name_plural': 'Коммуникации',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('vendor', utils.fields.ChoiceField(choices=[('klaviyo', 'Klaviyo'), ('whatsapp', 'Whatsapp')], max_length=8)),
                ('type', models.CharField(choices=[('accounts_login', 'Пользователь авторизовался'), ('accounts_signup', 'Пользователь зарегистрировался'), ('accounts_password_changed', 'Пользователь сменил пароль'), ('accounts_password_reset', 'Восстановление пароля'), ('accounts_password_reset_otp', 'Восстановление пароля одноразовым кодом'), ('accounts_password_set', 'Создание нового пароля'), ('accounts_email_confirm', 'Подтверждение адреса эл. почты')], max_length=50)),
                ('klaviyo_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='klaviyo.klaviyoevent')),
                ('whatsapp_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='whatsapp.whatsapptemplate')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['type'],
                'unique_together': {('vendor', 'type')},
            },
        ),
    ]
