# Generated by Django 3.2.3 on 2021-05-21 05:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_better_admin_arrayfield.models.fields
import model_utils.fields
import simple_history.models
import utils.fields
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('question', models.TextField()),
                ('teaser', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('slug', utils.fields.SlugField()),
                ('on_general', models.BooleanField(default=False)),
                ('order', utils.fields.OrderField(db_index=True, default=0, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('delay', models.PositiveIntegerField(default=0)),
                ('send_time', models.TimeField(blank=True, null=True)),
                ('delay_type', models.CharField(choices=[('days', 'Days'), ('hours', 'Hours'), ('minutes', 'Minutes'), ('seconds', 'Seconds')], default='minutes', max_length=7)),
                ('delay_seconds', models.IntegerField(editable=False)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='communication.flow')),
            ],
            options={
                'ordering': ('delay_seconds',),
            },
        ),
        migrations.CreateModel(
            name='FlowEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SendgridTemplate',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('template_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=255)),
                ('active_version_id', models.CharField(editable=False, max_length=255, null=True)),
                ('subject', models.CharField(editable=False, max_length=255, null=True)),
                ('preview_url', models.URLField(editable=False, null=True)),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('context', models.JSONField(blank=True, encoder=utils.models.JSONEncoder, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('start_date', utils.fields.RoundedDateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('trigger_type', models.CharField(choices=[('manual', 'Ручная'), ('automatic', 'Автоматическая'), ('user', 'Пользователь')], default='automatic', max_length=9)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='communication.flow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserFlowAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('eta', models.DateTimeField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='communication.flowaction')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='communication.userflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('mail', 'Письмо'), ('sms', 'SMS')], default='mail', max_length=20)),
                ('bcc_emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None)),
                ('sendgrid_template', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.sendgridtemplate')),
            ],
            options={
                'verbose_name': 'Шаблон',
                'verbose_name_plural': 'Шаблоны',
            },
        ),
        migrations.CreateModel(
            name='HistoricalTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.TextField()),
                ('type', models.CharField(choices=[('mail', 'Письмо'), ('sms', 'SMS')], default='mail', max_length=20)),
                ('bcc_emails', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sendgrid_template', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='communication.sendgridtemplate')),
            ],
            options={
                'verbose_name': 'historical Шаблон',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFAQ',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', utils.fields.ActiveField(db_index=True, default=True, verbose_name='Активный')),
                ('question', models.TextField()),
                ('teaser', models.TextField()),
                ('answer', ckeditor.fields.RichTextField()),
                ('slug', utils.fields.SlugField()),
                ('on_general', models.BooleanField(default=False)),
                ('order', utils.fields.OrderField(db_index=True, default=0, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical faq',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='flowaction',
            name='template',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, to='communication.template'),
        ),
        migrations.AddField(
            model_name='flow',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='communication.flowevent'),
        ),
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('hash', models.SlugField()),
                ('direction', models.CharField(choices=[('incoming', 'Входящая'), ('outgoing', 'Исходящая')], default='outgoing', max_length=50)),
                ('target', models.CharField(max_length=50)),
                ('trigger_type', models.CharField(choices=[('manual', 'Ручная'), ('automatic', 'Автоматическая'), ('user', 'Пользователь')], default='automatic', max_length=20)),
                ('type', models.CharField(choices=[('mail', 'Письмо'), ('sms', 'SMS')], default='mail', max_length=20)),
                ('sent', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_communications', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.communicationhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to=settings.AUTH_USER_MODEL)),
                ('user_flow_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.userflowaction')),
            ],
            options={
                'verbose_name': 'Коммуникация',
                'verbose_name_plural': 'Коммуникации',
            },
        ),
    ]
